language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
notifications:
  slack: jsidwebsolutions:rdCC7wPHTsCCJEuLdhwVr3Pu
deploy:
  provider: heroku
  app: flickr-scanner
  api_key: "dd732d5bf18096feeb2a8bd084e3b0a27c83752a"  
